package vista;

import modelo.Usuario;
import modelo.Restaurante;
import controlador.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Javier
 */
public class CristEatGUI extends javax.swing.JFrame {

	ControladorRestaurantes contRestaurantes;
	ControladorUsuarios contUsuarios;
	
	/**
	 * Creates new form CristEatGUI
	 */
	public CristEatGUI() {
		initComponents();
		contRestaurantes = null;
		contUsuarios = null;
	}
	
	public CristEatGUI(String ip, String puerto, String bdName, String user, String passw){
		initComponents();
		contRestaurantes = new ControladorRestaurantes(ip, puerto, bdName, user, passw);
		contUsuarios = new ControladorUsuarios(ip, puerto, bdName, user, passw);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPane_Tablas = new javax.swing.JTabbedPane();
        jTabbedPane_consultas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Usuarios = new javax.swing.JTable();
        jButton_refrescarUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Restaurantes = new javax.swing.JTable();
        jButton_refrescarRestaurantes = new javax.swing.JButton();
        jTabbedPane_insertar = new javax.swing.JTabbedPane();
        jPanel_insAlumnos = new javax.swing.JPanel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_login = new javax.swing.JLabel();
        jLabel_passw = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_login = new javax.swing.JTextField();
        jButton_insAlumno = new javax.swing.JButton();
        jPasswordField_passw = new javax.swing.JPasswordField();
        jPanel_insRestaurantes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CristEat");

        jTable_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Login", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Usuarios);

        jButton_refrescarUsuarios.setText("Refrescar");
        jButton_refrescarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_refrescarUsuarios)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_refrescarUsuarios)
                .addContainerGap())
        );

        jTabbedPane_consultas.addTab("Usuarios", jPanel1);

        jTable_Restaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Dirección", "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Restaurantes);

        jButton_refrescarRestaurantes.setText("Refrescar");
        jButton_refrescarRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarRestaurantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_refrescarRestaurantes)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_refrescarRestaurantes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_consultas.addTab("Restaurantes", jPanel2);

        jTPane_Tablas.addTab("Consultar", jTabbedPane_consultas);

        jLabel_id.setText("ID");

        jLabel_login.setText("Login");

        jLabel_passw.setText("Password");

        jButton_insAlumno.setText("Crear");
        jButton_insAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_insAlumnosLayout = new javax.swing.GroupLayout(jPanel_insAlumnos);
        jPanel_insAlumnos.setLayout(jPanel_insAlumnosLayout);
        jPanel_insAlumnosLayout.setHorizontalGroup(
            jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insAlumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_insAlumno)
                .addContainerGap())
            .addGroup(jPanel_insAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_insAlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel_id)
                        .addGap(59, 59, 59)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_insAlumnosLayout.createSequentialGroup()
                        .addGroup(jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_login)
                            .addComponent(jLabel_passw))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jPanel_insAlumnosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField_passw, jTextField_id, jTextField_login});

        jPanel_insAlumnosLayout.setVerticalGroup(
            jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_login)
                    .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_insAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_passw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_passw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jButton_insAlumno)
                .addContainerGap())
        );

        jPanel_insAlumnosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordField_passw, jTextField_id});

        jTabbedPane_insertar.addTab("Usuarios", jPanel_insAlumnos);

        javax.swing.GroupLayout jPanel_insRestaurantesLayout = new javax.swing.GroupLayout(jPanel_insRestaurantes);
        jPanel_insRestaurantes.setLayout(jPanel_insRestaurantesLayout);
        jPanel_insRestaurantesLayout.setHorizontalGroup(
            jPanel_insRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanel_insRestaurantesLayout.setVerticalGroup(
            jPanel_insRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jTabbedPane_insertar.addTab("Restaurantes", jPanel_insRestaurantes);

        jTPane_Tablas.addTab("Insertar", jTabbedPane_insertar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPane_Tablas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPane_Tablas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_refrescarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarUsuariosActionPerformed
		ArrayList<Usuario> usuarios = contUsuarios.getUsuarios();
		Usuario aux = null;
		//Reiniciamos la tabla
		((DefaultTableModel)jTable_Usuarios.getModel()).setRowCount(0);
		
		//Rellenamos los usuarios
		for (int i = 0; i < usuarios.size(); i++){
			aux = usuarios.get(i);
			((DefaultTableModel)jTable_Usuarios.getModel()).addRow(new Object[]{aux.getId(), aux.getLogin(), aux.getPassw()});
		}
		
    }//GEN-LAST:event_jButton_refrescarUsuariosActionPerformed

    private void jButton_refrescarRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarRestaurantesActionPerformed
        ArrayList<Restaurante> restaurantes = contRestaurantes.getRestaurantes();
		Restaurante aux = null;
		
		//Reiniciamos la tabla
		((DefaultTableModel)jTable_Restaurantes.getModel()).setRowCount(0);
		
		//Rellenamos los restaurantes
		for (int i = 0; i < restaurantes.size(); i++){
			aux = restaurantes.get(i);
			((DefaultTableModel)jTable_Restaurantes.getModel()).addRow(new Object[]{aux.getId(), aux.getNombre(), aux.getDireccion(), aux.getCategoria()});
		}
    }//GEN-LAST:event_jButton_refrescarRestaurantesActionPerformed

    private void jButton_insAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insAlumnoActionPerformed
        contUsuarios.addUsuario(jTextField_id.getText(), jTextField_login.getText(), jPasswordField_passw.getText());
    }//GEN-LAST:event_jButton_insAlumnoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CristEatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CristEatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CristEatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CristEatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CristEatGUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_insAlumno;
    private javax.swing.JButton jButton_refrescarRestaurantes;
    private javax.swing.JButton jButton_refrescarUsuarios;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_passw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_insAlumnos;
    private javax.swing.JPanel jPanel_insRestaurantes;
    private javax.swing.JPasswordField jPasswordField_passw;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTPane_Tablas;
    private javax.swing.JTabbedPane jTabbedPane_consultas;
    private javax.swing.JTabbedPane jTabbedPane_insertar;
    private javax.swing.JTable jTable_Restaurantes;
    private javax.swing.JTable jTable_Usuarios;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_login;
    // End of variables declaration//GEN-END:variables
}
